[package]
name = "task-reminder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
time = { version = "0.3.15", features = ["local-offset", "serde", "macros"] }
uuid = { version = "1.1.2", features = ["v4", "serde"] }

[dev-dependencies]
tempfile = "3.3.0"

[features]
